### ISSUE TITLE
HTTPヘッダを変えたい

### ISSUE THREAD

**Issue by coexe** [skk-users-jp/skk-plus-dic#2]
`curl -v http://skk-users.jp/skk-plus-dic/skk-plus.txt`
してみると鯖応答が強制的にUTF-8になってしまっています。

```
> GET /skk-plus-dic/skk-plus.txt HTTP/1.1
> Host: skk-users.jp
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Server: GitHub.com
< Date: Sun, 12 Feb 2017 05:47:47 GMT
< Content-Type: text/plain; charset=utf-8
                                           ^^^^^^^^
< Content-Length: 4806
< Last-Modified: Sat, 04 Feb 2017 16:54:38 GMT
< Access-Control-Allow-Origin: *
< Expires: Sun, 12 Feb 2017 05:57:47 GMT
< Cache-Control: max-age=600
< Accept-Ranges: bytes
< X-GitHub-Request-Id: B2F0:77F1:27A1778:33475DA:589FF703
```

ここをファイル名によって任意の文字列を返せるように制御したいんですがよい方法はないでしょうか。
あと http://skk-users.jp/skk-plus-dic/ も日本語ページなのにHTMLソースにlang=enと書かれてしまっていて、これをjpに書き換えたいと思ってます。
このあたりの設定サンプルなど参考になりそうな情報はないでしょうか……？

**Comment by zonuexe** [comment]
@coexe なるほど…

 http://skk-users.jp/skk-plus-dic/  の方は `README.md` が自動変換されてるっぽいので `index.html` を置いてやれば解決します。

`Content-Type: text/plain; charset=utf-8` の方はちょっとどうにもならない予感がしてるので、必要なら別のVPSとかで配信することも検討します。

**Comment by zonuexe** [comment]
@coexe 
こちらの件、 `dic.skk-users.jp` で利用できるようにしました。

* HTTPでアクセスできます http://dic.skk-users.jp/skk-plus/skk-plus.txt
* [HSTS](https://ja.wikipedia.org/wiki/HTTP_Strict_Transport_Security)の設定が入ってるので、対応のブラウザは自動でhttpsになります
* Jenkinsで自動化してありますので、`git push`して1〜2分程度待てば反映されます

確認していただいたら、このリポジトリのGitHub Pagesは無効化します。

**Comment by coexe** [comment]
なるほど異空間に飛ばすとはナイスハックですね！
・Firefox 51でブラウザ側のｔext/plainの自動判定が動いていること
・JScriptで書いたhttps未対応のダウンローダでもきちんとダウンロードできたこと
を確認できましたので閲覧・配布ともに問題ありません。ありがとうございました！

**Comment by zonuexe** [comment]
@skk-users-jp/maintainers `gh-pages` ブランチを削除して `master` 一本にしました
