### ISSUE TITLE
SKK plus Dictionary files access issue.

### ISSUE THREAD

**Issue by MAMEDEKA** [skk-users-jp/skk-plus-dic#3]
以下が404でアクセス出来ないようです。
対象ファイルはgithubからはダウンロード可能です。

http://dic.skk-users.jp/skk-plus/
http://dic.skk-users.jp/skk-plus/skk-plus.txt
http://dic.skk-users.jp/skk-plus/skk-plus_azik.txt

**Comment by coexe** [comment]
ご報告ありがとうございます。去年末くらいから少々調子が悪いっぽいです。
ひとまず私のWebサイトでURL末尾を同名のものにすればダウンロードできるようにしてありますので、当面はそれで切り抜けてください。

**Comment by coexe** [comment]
ご報告ありがとうございます。すぐには直せないかもしれませんので当面はgithubや以下から直接ダウンロードをお願いします。
http://coexe.web.fc2.com/skk-plus.txt
http://coexe.web.fc2.com/skk-plus_azik.txt

**Comment by coexe** [comment]
URLが変わってリニューアルしました
